# Required event block
events {
    worker_connections 4096;
}

http {
    # 1. Define your cluster of workers
    upstream gpu_cluster {
        # This tells NGINX to use the "Least Connections" algorithm
        #least_conn; 

        # IMPORTANT: Replace the X's with Laptop 2's ZeroTier IP
        #server 10.2.213.82:8000; # Seif
        server 10.2.213.176:8000; # Sallam
        server 10.2.213.91:8000; # Roger
        server 10.2.213.8:8000; # Ashraf
        server 10.2.213.81:8000; # Andrew
        keepalive 256;
    }

    # 2. Define the Master Server (Listening on Port 80)
    server {
        listen 80;

        # 3. Route incoming /process requests to the cluster
        location /process {
            proxy_pass http://gpu_cluster;
            
            # These headers ensure the worker knows where the request originally came from
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Connection ""; # Clear 'close' header
            proxy_next_upstream error timeout http_504 http_502;
            proxy_next_upstream_tries 3;        # Try up to 3 different workers
            proxy_next_upstream_timeout 160s;    # Give up retrying after 30s

        }
    }
}

