# Required event block
events {
    worker_connections 1024;
}

http {
    # 1. Define your cluster of workers
    upstream gpu_cluster {
        # This tells NGINX to use the "Least Connections" algorithm
        #least_conn; 

        # IMPORTANT: Replace the X's with Laptop 2's ZeroTier IP
        server 10.2.213.82:8000; 
        server 10.2.213.176:8000;
        server 10.2.213.91:8000;
        server 10.2.213.8:8000;
    }

    # 2. Define the Master Server (Listening on Port 80)
    server {
        listen 80;

        # 3. Route incoming /process requests to the cluster
        location /process {
            proxy_pass http://gpu_cluster;
            
            # These headers ensure the worker knows where the request originally came from
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}